dataset_path: "../datasets/MEDIC/data/multimodal-deep-learning-disaster-response-mouzannar/multimodal"
learning_rate: 0.0001
split_ratio: 0.9
start_epoch: 1
epoch: 15
checkpoint_dir: "chkpt/vision_transformer"
checkpoint_epoch: 1
batch_size: 32